version: "3.1"

services:
  web:
    build:
      context: .
      dockerfile: docker/Web.Dockerfile

    ports:
      - 8010:8010

  admin:
    build:
      context: .
      dockerfile: docker/Admin.Dockerfile

    ports:
      - 8020:8020

  proxy:
    build:
      context: .
      dockerfile: docker/Proxy.Dockerfile

    ports:
      - 80:80
